// Emotion → CSS color mapping for Chromatic Emotion design system
// Used by: generate/route.ts (server), GachaQuiz.tsx (client)

export const EMOTION_COLORS: Record<string, string> = {
  '穏やか':   '#00B4A8',
  '不安':     '#4060C0',
  '感謝':     '#D4A030',
  '怒り':     '#C02020',
  '興奮':     '#E06000',
  '疲労':     '#506070',
  '虚無':     '#404050',
  '希望':     '#00E5C8',
  '悲しみ':   '#3050A0',
  '喜び':     '#E0C000',
  '迷い':     '#8060C0',
  '決意':     '#00C090',
  '孤独':     '#203060',
  '愛':       '#E05080',
  '恐れ':     '#703030',
  '誇り':     '#C08020',
  '焦り':     '#E05020',
  '解放感':   '#00D4E0',
  '懐かしさ': '#C09060',
  '期待':     '#00A8E0',
  '寂しさ':   '#6080A0',
  '驚き':     '#A0E000',
  '安堵':     '#60A040',
  '羨望':     '#6040A0',
  '満足':     '#D0A000',
  '後悔':     '#805040',
  '勇気':     '#E07000',
  '混乱':     '#8040C0',
  '平和':     '#40A090',
  '渇望':     '#C04060',
}

// Emotion → personalized loading copy (English)
export const EMOTION_LOADING_COPY: Record<string, string> = {
  '穏やか':   'Weaving stillness into melody...',
  '不安':     'Turning your worry into waves...',
  '感謝':     'Wrapping gratitude in sound...',
  '怒り':     'Forging your fire into rhythm...',
  '興奮':     'Electrifying the air around you...',
  '疲労':     'Finding rest in quiet notes...',
  '虚無':     'Shaping silence into something...',
  '希望':     'Lifting your hope on wings of sound...',
  '悲しみ':   'Weaving your grief into strings...',
  '喜び':     'Dancing your joy into melody...',
  '迷い':     'Navigating your crossroads in sound...',
  '決意':     'Carving your resolve into rhythm...',
  '孤独':     'Filling the quiet with your presence...',
  '愛':       'Pouring your love into every note...',
  '恐れ':     'Transforming fear into something beautiful...',
  '誇り':     'Capturing your pride in sound...',
  '焦り':     'Channeling urgency into motion...',
  '解放感':   'Unfolding your freedom into sound...',
  '懐かしさ': 'Summoning memories in melody...',
  '期待':     "Composing the feeling of what's coming...",
  '寂しさ':   'Turning loneliness into a companion...',
  '驚き':     'Crystallizing your wonder into sound...',
  '安堵':     'Breathing relief into every note...',
  '羨望':     'Chasing what you long for in sound...',
  '満足':     'Settling your contentment into harmony...',
  '後悔':     'Turning what you wish were different into beauty...',
  '勇気':     'Summoning courage into melody...',
  '混乱':     'Finding form in your chaos...',
  '平和':     'Distilling peace into sound...',
  '渇望':     'Reaching for what you need in melody...',
}
