// Emotion → CSS color mapping for Chromatic Emotion design system
// Keys are English slugs matching messages/en.json emotions.*
// Used by: generate/route.ts (server), GachaQuiz.tsx (client)

export const EMOTION_COLORS: Record<string, string> = {
  'calm':         '#00B4A8',
  'anxiety':      '#4060C0',
  'gratitude':    '#D4A030',
  'anger':        '#C02020',
  'excitement':   '#E06000',
  'fatigue':      '#506070',
  'emptiness':    '#404050',
  'hope':         '#00E5C8',
  'sadness':      '#3050A0',
  'joy':          '#E0C000',
  'confusion':    '#8060C0',
  'resolve':      '#00C090',
  'solitude':     '#203060',
  'love':         '#E05080',
  'fear':         '#703030',
  'pride':        '#C08020',
  'urgency':      '#E05020',
  'liberation':   '#00D4E0',
  'nostalgia':    '#C09060',
  'anticipation': '#00A8E0',
  'loneliness':   '#6080A0',
  'wonder':       '#A0E000',
  'relief':       '#60A040',
  'envy':         '#6040A0',
  'contentment':  '#D0A000',
  'regret':       '#805040',
  'courage':      '#E07000',
  'chaos':        '#8040C0',
  'peace':        '#40A090',
  'longing':      '#C04060',
}

// Emotion → personalized loading copy (English)
export const EMOTION_LOADING_COPY: Record<string, string> = {
  'calm':         'Weaving stillness into melody...',
  'anxiety':      'Turning your worry into waves...',
  'gratitude':    'Wrapping gratitude in sound...',
  'anger':        'Forging your fire into rhythm...',
  'excitement':   'Electrifying the air around you...',
  'fatigue':      'Finding rest in quiet notes...',
  'emptiness':    'Shaping silence into something...',
  'hope':         'Lifting your hope on wings of sound...',
  'sadness':      'Weaving your grief into strings...',
  'joy':          'Dancing your joy into melody...',
  'confusion':    'Navigating your crossroads in sound...',
  'resolve':      'Carving your resolve into rhythm...',
  'solitude':     'Filling the quiet with your presence...',
  'love':         'Pouring your love into every note...',
  'fear':         'Transforming fear into something beautiful...',
  'pride':        'Capturing your pride in sound...',
  'urgency':      'Channeling urgency into motion...',
  'liberation':   'Unfolding your freedom into sound...',
  'nostalgia':    'Summoning memories in melody...',
  'anticipation': "Composing the feeling of what's coming...",
  'loneliness':   'Turning loneliness into a companion...',
  'wonder':       'Crystallizing your wonder into sound...',
  'relief':       'Breathing relief into every note...',
  'envy':         'Chasing what you long for in sound...',
  'contentment':  'Settling your contentment into harmony...',
  'regret':       'Turning what you wish were different into beauty...',
  'courage':      'Summoning courage into melody...',
  'chaos':        'Finding form in your chaos...',
  'peace':        'Distilling peace into sound...',
  'longing':      'Reaching for what you need in melody...',
}
